name: Build documentation

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches: [main,dev]
#  push:
#    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  docs:
    name: Ford-docs
    runs-on: [ubuntu-latest]
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
      - run: |
          python -m pip install ford
          ford README.md
      - uses: actions/upload-artifact@v4
        with:
          name: ford-docs
          path: doc

