name: Setup Fortran

on:
  workflow_dispatch:
    branches: [*]
  pull_request:
    branches: [main]
#  push:
#    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.os }}-${{ matrix.toolchain.compiler }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        toolchain:
          - {compiler: gcc, version: 13}
          - {compiler: intel, version: '2025.0'}
          - {compiler: intel-classic, version: '2021.10'}
          - {compiler: nvidia-hpc, version: '25.1'}
          - {compiler: lfortran, version: '0.45.0'}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0          
      - uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}
      - uses: fortran-lang/setup-fpm@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          # Build with FPM
          fpm build --compiler ${{ env.FPM_FC }}
