name: Setup Fortran

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        toolchain:
          - {compiler: gcc, version: 13}
          - {compiler: intel, version: '2025.0'}
          - {compiler: intel-classic, version: '2021.10'}
          - {compiler: nvidia-hpc, version: '25.1'}
          - {compiler: lfortran, version: '0.45.0'}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}

      - run: |
          # environment vars FC, CC, and CXX are set
          ${{ env.FC }} *f90 -o test || true
          # We run this twice because of the hacky way we are
          # building, remove once we have a proper build system
          ${{ env.FC }} *f90 -o test
