name: Setup Fortran

on:
  workflow_dispatch:
  pull_request:
    branches: [main,dev]
#  push:
#    branches: [main]


permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.os }}-${{ matrix.toolchain.compiler }}
    runs-on: ${{ matrix.os }}
    env:
      FPM_FFLAGS: ${{ matrix.toolchain.FPM_FFLAGS }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        toolchain:
          - {compiler: gcc, version: 14, FPM_FFLAGS: "-Werror=unused --coverage"}
          - {compiler: intel, version: '2025.0'}
          - {compiler: intel-classic, version: '2021.10'}
          - {compiler: nvidia-hpc, version: '25.1'}
          # lfortran can't compile the code at the moment, we will
          # keep an eye on the progress of the project in the hope
          # that we can add this back in the future
          # - {compiler: lfortran, version: '0.49.0'}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}
      - uses: fortran-lang/setup-fpm@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  
      - run: |
          # Build and test code using FPM
          fpm test

      - name: Generate code coverage report
        if: ${{ matrix.toolchain.compiler == 'gcc' }}
        run: |
          gcov ./build/gfortran*/Bio-CFD/*.gcda -r 

      - name: Setup LCOV
        if: ${{ matrix.toolchain.compiler == 'gcc' }}
        uses: hrishikesh-kadam/setup-lcov@v1

      - name: Remove folders from coverage report
        if: ${{ matrix.toolchain.compiler == 'gcc' }}
        run: |
          lcov --directory . --capture --output-file coverage.info --gcov-tool gcov
          lcov --remove coverage.info "$PWD/test/*" --output-file coverage.info
          lcov --remove coverage.info "$PWD/build/*" --output-file coverage.info

      - name: Report code coverage as comment
        if: ${{ matrix.toolchain.compiler == 'gcc' }}
        uses: zgosalvez/github-actions-report-lcov@v4
        with:
          coverage-files: coverage.info
          minimum-coverage: 0
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: src
          update-comment: true
